import { useState, useEffect } from "react";
import "../pages/WYR.css"
const questions = [
    "Would you rather go on a spontaneous road trip or have a perfectly planned vacation?",
    "Would you rather never argue or never have disagreements again?",
    "Would you rather cook together every night or order in and relax together?",
    "Would you rather always be honest but hurt each other sometimes or avoid conflict even if it means lying?",
    "Would you rather have unlimited money but never have time together, or limited money but lots of quality time?",
    "Would you rather move to a new city together or stay close to family?",
    "Would you rather always remember every detail of your relationship or forget the bad moments?",
    "Would you rather share a hobby you love with your partner or discover a new hobby together?",
    "Would you rather be the funny one or the romantic one in the relationship?",
    "Would you rather spend a year apart growing individually or stay together but feel stagnant?",
    "Would you rather have a weekend full of adventure or a weekend full of relaxation?",
    "Would you rather be able to read each other’s minds or always communicate perfectly verbally?",
    "Would you rather have a small wedding now or a big wedding later?",
    "Would you rather give up social media for a year together or never go on a vacation together?",
    "Would you rather adopt a pet together or travel the world first?",
    "Would you rather stay in a cozy apartment or live in a spacious house?",
    "Would you rather always be cold together or always be hot together?",
    "Would you rather plan surprises for each other or be surprised often?",
    "Would you rather argue about money or argue about household chores?",
    "Would you rather have a night out dancing or a night in binge-watching shows?",
    "Would you rather take a cooking class together or a dance class?",
    "Would you rather be famous together or live anonymously?",
    "Would you rather face challenges together or face no challenges but feel less connected?",
    "Would you rather celebrate holidays in your hometown or explore new traditions together?",
    "Would you rather go to a music festival or a luxury spa weekend?",
    "Would you rather have kids early or wait until later in life?",
    "Would you rather live by the beach or in the mountains?",
    "Would you rather always agree or always challenge each other intellectually?",
    "Would you rather be each other’s biggest supporter or strongest critic?",
    "Would you rather travel for work separately or work together remotely?",
    "Would you rather give each other thoughtful gifts or write love letters?",
    "Would you rather try every type of cuisine together or stick to your favorites?",
    "Would you rather take a risk in love or play it safe?",
    "Would you rather spend every anniversary abroad or celebrate at home?",
    "Would you rather be spontaneous in love or planned in love?",
    "Would you rather laugh every day together or have deep meaningful conversations every day?",
    "Would you rather have a home full of plants or a home full of tech gadgets?",
    "Would you rather surprise each other with dates or plan every date together?",
    "Would you rather sing together in the car or dance together in the kitchen?",
    "Would you rather take turns planning trips or plan together every time?",
    "Would you rather have a home library or a home theater?",
    "Would you rather experience extreme sports or relaxing retreats together?",
    "Would you rather be the first to apologize or the first to forgive?",
    "Would you rather share a single passion or have separate passions that inspire each other?",
    "Would you rather go back in time to relive a memory together or see a future memory?",
    "Would you rather always have the perfect gift ideas or perfect date ideas?",
    "Would you rather have endless money for experiences or endless money for material things?",
    "Would you rather have a surprise weekend getaway or a planned long vacation?",
    "Would you rather always know what the other is thinking or always know how they feel?",
    "Would you rather laugh at your partner’s mistakes or cry together during tough times?",
    "Would you rather have a quiet night in or a lively night out?",
    "Would you rather discover a secret together or keep it to yourselves?",
    "Would you rather face fears together or face comfort zones together?",
    "Would you rather explore space or explore the deepest parts of the ocean?",
    "Would you rather have the ability to time travel but only to the past or only to the future?",
    "Would you rather know the exact date of your death or the cause of your death?",
    "Would you rather be famous for your intelligence or famous for your creativity?",
    "Would you rather live without the internet or live without air conditioning and heating?",
    "Would you rather instantly learn every language or instantly master every instrument?",
    "Would you rather have unlimited free time but no money or unlimited money but no free time?",
    "Would you rather live in a utopia with no privacy or in a dystopia with full privacy?",
    "Would you rather have the ability to change one decision from your past or see one decision in your future?",
    "Would you rather be able to stop time for everyone but yourself or slow down time for yourself only?",
    "Would you rather lose the ability to read or lose the ability to speak?",
    "Would you rather live a short life full of adventure or a long life full of comfort?",
    "Would you rather be able to communicate with animals or speak every human language fluently?",
    "Would you rather live in a world without music or a world without movies?",
    "Would you rather have your dream job but be constantly stressed or a mediocre job with total peace?",
    "Would you rather know every secret of the universe or remain blissfully unaware?",
    "Would you rather give up your favorite food forever or your favorite hobby forever?",
    "Would you rather have a rewind button or a pause button for your life?",
    "Would you rather find true love but lose all your friends or keep all your friends but never find love?",
    "Would you rather live in a futuristic city or a medieval village?",
    "Would you rather be able to read minds but hear everyone’s thoughts all the time or never read minds again?",
    "Would you rather be immortal but bored forever or live a normal lifespan full of excitement?",
    "Would you rather have perfect health but no memories or imperfect health with all your memories intact?",
    "Would you rather have the power of invisibility or the power of super strength?",
    "Would you rather live without music or without movies for the rest of your life?",
    "Would you rather be the smartest person in the world or the richest?",
    "Would you rather fight one horse-sized duck or 100 duck-sized horses?",
    "Would you rather experience life as someone else for a week or have someone else live your life for a week?",
    "Would you rather never sleep again or never eat again?",
    "Would you rather know the truth about everything or be blissfully ignorant?",
    "Would you rather always have the newest technology but never get to upgrade or use old tech forever but have it fully upgraded?",
    "Would you rather live in total silence or live in total noise?",
    "Would you rather be able to teleport anywhere or be able to fly, but slowly?",
    "Would you rather have a perfect memory or the ability to forget anything at will?",
    "Would you rather live without your phone or without your computer?",
    "Would you rather have a constant craving for something sweet or something salty?",
    "Would you rather always know when someone is lying to you or never be able to lie yourself?",
    "Would you rather explore a new planet or a hidden part of Earth?",
    "Would you rather always feel cold or always feel hot?",
    "Would you rather have the ability to predict the future but never change it or change the future but never know the outcome?",
    "Would you rather be feared by everyone or loved by a few?",
    "Would you rather never feel physical pain or never feel emotional pain?",
    "Would you rather live in a world without color or a world without sound?",
    "Would you rather experience a day from the life of a billionaire or a day from the life of a world traveler?",
    "Would you rather have no one show up to your birthday or everyone forget it?",
    "Would you rather be famous in history books or in social media?",
    "Would you rather solve one huge world problem or solve a million small personal problems?",
    "Would you rather always be stuck in traffic or always miss your flight?",
    "Would you rather be able to change the past but risk altering the present or leave the past alone?",
    "Would you rather live on Mars for a year or the bottom of the ocean for a year?",
    "Would you rather have infinite knowledge or infinite creativity?", "Would you rather accidentally send a drunken text to your boss or your ex?",
    "Would you rather get arrested for stealing a million dollars or get away with stealing $100 but be haunted by guilt?",
    "Would you rather go streaking once in public or scream your secrets on a rooftop?",
    "Would you rather prank your parents in a wild way or prank your friends in a way that could backfire?",
    "Would you rather do karaoke drunk in front of strangers or sober in front of friends?",
    "Would you rather go to a wild music festival with zero rules or a fancy dinner where anything embarrassing could happen?",
    "Would you rather try a strange exotic food that’s rumored to be addictive or stick to safe foods forever?",
    "Would you rather have your most embarrassing drunk moment go viral or a boring but humiliating moment?",
    "Would you rather accidentally steal someone’s partner or be accidentally stolen from?",
    "Would you rather take a tattoo you regret or a piercing that permanently changes your look?",
    "Would you rather attend a secret underground party or a public scandalous event?",
    "Would you rather binge drink with friends and wake up missing things or stay sober and always feel left out?",
    "Would you rather cheat once and get caught or never cheat but always wonder ‘what if’?",
    "Would you rather be known for outrageous stories or for being completely mysterious?",
    "Would you rather prank someone and it goes horribly wrong or get pranked yourself in a wild way?",
    "Would you rather go skinny dipping in public or streak through a major city?",
    "Would you rather try a dangerous stunt for fame or a dangerous stunt for money?",
    "Would you rather accidentally insult someone famous or be publicly roasted yourself?",
    "Would you rather sneak into a VIP party and get kicked out or never get in but tell everyone you did?",
    "Would you rather be hooked on caffeine or hooked on nicotine for a year?",
    "Would you rather accidentally broadcast a private moment or broadcast something awkward by mistake?",
    "Would you rather go on a crazy adventure with no plan or a boring trip with a perfect itinerary?",
    "Would you rather gamble everything once and maybe win big or play it safe forever?",
    "Would you rather get caught sneaking into a movie or sneaking out of work early?",
    "Would you rather have a wild night out and regret nothing or a calm night and regret missing the chaos?",
    "Would you rather accidentally like your ex’s photo from 3 years ago or post something embarrassing online?",
    "Would you rather drink something mysterious that tastes awful or eat something mysterious that could be dangerous?",
    "Would you rather party with celebrities and get exposed or party with friends and stay low-key?",
    "Would you rather tell your worst secret to a stranger or hear theirs?",
    "Would you rather be blacklisted from a club or blacklisted from a social circle forever?",
    "Would you rather get publicly humiliated on live TV or on social media?",
    "Would you rather prank your boss in a funny way or prank your parents in a risky way?",
    "Would you rather go to a festival where anything goes or a festival with strict rules?",
    "Would you rather accidentally reveal your deepest fantasy to your friends or to your family?",
    "Would you rather get lost in a foreign city high or sober?",
    "Would you rather have a scandalous story attached to your name or be completely forgotten?",
    "Would you rather take an extreme dare or watch your best friend take it?",
    "Would you rather party for a month straight and be exhausted or relax for a month and feel bored?",
    "Would you rather start a rumor that ruins someone’s weekend or have one started about you?",
    "Would you rather have a wild night you can’t remember or a boring night you remember perfectly?",
    "Would you rather try illegal street food that’s amazing or safe but boring gourmet food?",
    "Would you rather accidentally hack something minor but funny or major but easily fixable?",
    "Would you rather be famous for something wild or infamous for something tame?",
    "Would you rather sneak into an adult-only event or get kicked out publicly?",
    "Would you rather binge a new drug or binge a new TV series for 24 hours straight?",
    "Would you rather have a public fight that everyone talks about or a private fight no one knows?",
    "Would you rather get dared to streak at a sporting event or prank call a celebrity?",
    "Would you rather party with total strangers and never see them again or party with friends and regret nothing?",
    "Would you rather steal candy from a baby or accidentally insult a child in public?",
    "Would you rather live in a world where everyone’s thoughts are visible or where everyone’s dreams are recorded for you to watch?",
    "Would you rather be stuck in a loop of your favorite day forever or never remember it at all?",
    "Would you rather have taste but no smell or smell but no taste?",
    "Would you rather time move backwards for a day or everyone else freeze for a day while you move?",
    "Would you rather your shadow have a mind of its own or your reflection in the mirror?",
    "Would you rather hear colors or see sounds?",
    "Would you rather sneeze confetti every time you sneeze or cry bubbles every time you cry?",
    "Would you rather swap lives with an alien for a week or with your pet?",
    "Would you rather be able to feel other people’s emotions physically or taste their memories?",
    "Would you rather have gravity reversed once a month or your body shrink and grow randomly?",
    "Would you rather have a personal theme song that everyone hears whenever you enter a room or a personal scent that everyone smells?",
    "Would you rather exist in two places at once or experience time in two different speeds?",
    "Would you rather float instead of walk or always feel weightless when you sit?",
    "Would you rather be constantly accompanied by a mysterious glowing orb or a tiny whispering cloud?",
    "Would you rather dream every night vividly and wake up exhausted or never dream but always feel energized?",
    "Would you rather see the internet physically manifest around you or see thoughts floating above people’s heads?",
    "Would you rather taste music or hear colors?",
    "Would you rather your hair grow uncontrollably when you feel strong emotions or your eyes change color?",
    "Would you rather smell emotions like perfume or taste emotions like candy?",
    "Would you rather everything you touch turn slightly alive or everything you see flicker like a glitch?",
    "Would you rather have a cloud follow you that occasionally rains random objects or a tree that grows wherever you sleep?",
    "Would you rather speak in rhymes forever or have everyone else speak in rhymes to you?",
    "Would you rather laugh uncontrollably whenever someone lies or cry uncontrollably whenever someone tells the truth?",
    "Would you rather always know the temperature of people’s souls or the weight of their hearts?",
    "Would you rather see a different version of reality every time you blink or hear a different soundtrack every time you walk?",
    "Would you rather taste your dreams for a day or have someone else taste them?",
    "Would you rather your thoughts appear as tiny floating lights or as words above your head?",
    "Would you rather everyone forget you exist for a day or remember every embarrassing thing you’ve ever done?",
    "Would you rather walk through walls like air or have walls move like water around you?",
    "Would you rather feel every second in slow motion for a day or all at once in a chaotic burst?",
    "Would you rather be able to speak to plants or to shadows?",
    "Would you rather smell the past or taste the future?",
    "Would you rather live a day as a cloud drifting aimlessly or a rock lying still?",
    "Would you rather your laughter create sparks of light or your tears create tiny plants?",
    "Would you rather perceive everyone’s aura in color or hear their inner monologue as music?",
    "Would you rather time only exist when you pay attention or reality resets every time you blink?",
    "Would you rather float in space alone forever or travel endlessly through infinite cities?",
    "Would you rather have a rewind button that only rewinds one minute at a time or fast forward button that skips one year?",
    "Would you rather taste the color blue or feel the sound of red?",
    "Would you rather your dreams physically appear for a few minutes when you wake or your nightmares follow you silently?",
    "Would you rather always see tiny versions of yourself everywhere or giant versions of everyone else?",
    "Would you rather speak in a language only animals understand or only inanimate objects understand?",
    "Would you rather float inside a bubble forever or shrink to the size of an ant permanently?",
    "Would you rather be able to breathe underwater but lose your sense of smell or fly but never feel touch again?",
    "Would you rather feel every emotion intensely for a day or feel nothing at all for a month?",
    "Would you rather exist in a looping dream or live a linear nightmare?",
    "Would you rather swap senses with someone randomly once a day or swap places with them randomly once a month?",
    "Would you rather see everyone’s past memories above their heads or their future above their feet?",
    "Would you rather be a ghost everyone ignores or a demon everyone fears but no one sees?",
    "Would you rather your shadow act out your hidden thoughts or your reflection act out your fears?",
    "Would you rather see the world in extreme detail forever or see it in abstract shapes forever?"
];

export default function WouldYouRather() {
    const [questionList, setQuestionList] = useState([...questions]);
    const [question, setQuestion] = useState("");

    const newQuestion = () => {
        if (questionList.length === 0) {
            setQuestion("No more questions!");
            return;
        }
        const randomIndex = Math.floor(Math.random() * questionList.length);
        setQuestion(questionList[randomIndex]);
    };

    const removeQuestion = () => {
        setQuestionList((prev) => prev.filter((q) => q !== question));
        newQuestion();
    };

    useEffect(() => {
        newQuestion();
    }, [questionList]);

    return (
        <div className="would-you-rather-container">
            <div className="question-box">{question}</div>
            <div style={{ display: "flex", gap: "15px" }}>
                <button onClick={newQuestion} className="new-question-btn">
                    New Question
                </button>
                <button
                    onClick={removeQuestion}
                    className="new-question-btn"
                    style={{ background: "#aaa" }}
                >
                    Stupid Question
                </button>
            </div>
        </div>
    );
}
